# Generated by Django 3.1.4 on 2021-05-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=255, verbose_name='Referência')),
                ('texto', models.TextField(verbose_name='Texto de Feedback')),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Link')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('qt_jogadores', models.PositiveSmallIntegerField(default=0, verbose_name='Quantidade de Players')),
                ('imagem', models.ImageField(upload_to='game_images', verbose_name='Imagem')),
                ('verificado', models.BooleanField(default=False, verbose_name='Verificado')),
            ],
        ),
    ]
